project:
  type: website

website:
  title: "ISSS626geo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Hands-on Exercise
        menu:
          - href: hands-on_ex01.qmd
            text: Hands-on 1
          - href: hands-on_ex02.qmd
            text: Hands-on 2
          - href: hands-on_ex03.qmd
            text: Hands-on 3
          - href: hands-on_ex04.qmd
            text: Hands-on 4
      - text: In-class
        menu:
          - href: In-class Exercise 4.qmd
            text: In-class Exercise 4
      - text: Take home Exercise
        menu:
          - href: take-home_ex01.qmd
            text: Technical Report 1
          - href: take-home_ex01_slides.qmd
            text: Executive Summary 1
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
